/**
 * `git-credential-uno` — GitHub on this computer through the Uno account.
 *
 * The person connects GitHub ONCE per account (the Uno GitHub App, the same
 * one that deploys their sites). From then on `git clone` / `git push` of a
 * private repository works on every cloud computer of the account: git asks
 * this helper, the helper asks the console with the computer's own machine
 * token, the console mints a GitHub token narrowed to that ONE repository
 * for one hour (fishcode `internal/api/work_git.go`).
 *
 * What it is careful about:
 * - nothing is ever written to disk — not to `.git/config`, not to a
 *   credential store (`store` / `erase` are no-ops);
 * - only `https://github.com/<owner>/<repo>` is answered, and only when git
 *   passes the repository path (`credential.useHttpPath`), so the console
 *   can narrow the token to that repository;
 * - when Uno has nothing to offer it stays silent on stdout: git moves on to
 *   the next helper (the person's own `gh`, a keychain) exactly as before;
 * - the helper is added to the global git config only on a cloud computer
 *   (machine token present), never on a person's own laptop, and it never
 *   removes or reorders helpers that are already there.
 *
 * The helper is one self-contained CommonJS file run by the same Node that
 * runs the daemon; it reads the machine token from the daemon's settings
 * file on every call (the console may write it after the daemon started).
 *
 * @module setupTools/gitCredentialHelper
 */

/** File name git derives the helper from (`git credential-uno`). */
export const GIT_CREDENTIAL_HELPER_NAME = "git-credential-uno";

export const GITHUB_CREDENTIAL_SECTION = "credential.https://github.com";

export interface GitCredentialHelperScriptInput {
  /** Absolute path of the runtime that executes the helper (`process.execPath`). */
  readonly nodePath: string;
  /** The daemon's `settings.json` (holds `uno.boxToken`, `uno.boxId`). */
  readonly settingsPath: string;
  /** The console, e.g. `https://console.uno4.dev`. */
  readonly baseUrl: string;
}

/**
 * The helper's source. Kept dependency-free and small on purpose: it runs on
 * every git network operation.
 */
export function gitCredentialHelperScript(input: GitCredentialHelperScriptInput): string {
  const body = String.raw`
// Generated by Uno Work — do not edit; it is rewritten when the app starts.
// git credential helper: GitHub through your Uno account (one repository, one hour).
"use strict";
const fs = require("node:fs");

const SETTINGS_PATH = __SETTINGS_PATH__;
const BASE_URL = __BASE_URL__;

function fail(message) {
  // stderr is shown by git next to its own error; stdout stays empty so git
  // tries the next helper.
  if (message) process.stderr.write("Uno: " + message + "\n");
  process.exit(0);
}

function readStdin() {
  try {
    return fs.readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function parseRequest(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const at = line.indexOf("=");
    if (at > 0) out[line.slice(0, at)] = line.slice(at + 1).replace(/\r$/, "");
  }
  return out;
}

function repositoryOf(path) {
  const clean = String(path || "").replace(/^\/+|\/+$/g, "").replace(/\.git$/i, "");
  return /^[A-Za-z0-9][A-Za-z0-9-]{0,38}\/[A-Za-z0-9_.-]{1,100}$/.test(clean) ? clean : null;
}

function machineCredentials() {
  try {
    const uno = (JSON.parse(fs.readFileSync(SETTINGS_PATH, "utf8")) || {}).uno || {};
    const token = typeof uno.boxToken === "string" ? uno.boxToken.trim() : "";
    const boxId = Number(uno.boxId);
    if (token && Number.isSafeInteger(boxId) && boxId > 0) return { token, boxId };
  } catch {}
  return null;
}

async function main() {
  // store / erase: nothing is kept anywhere, so there is nothing to do.
  if (process.argv[2] !== "get") return;
  const request = parseRequest(readStdin());
  if (request.protocol !== "https" || String(request.host || "").toLowerCase() !== "github.com") return;
  const repo = repositoryOf(request.path);
  if (repo === null) return;
  const creds = machineCredentials();
  if (creds === null) return;

  const base = (process.env.UNO_WORK_DEV_CONTROL_PLANE_URL || BASE_URL).replace(/\/+$/, "");
  let response;
  try {
    response = await fetch(base + "/api/v1/boxes/" + creds.boxId + "/work/git/github/token", {
      method: "POST",
      headers: { Authorization: "Bearer " + creds.token, "Content-Type": "application/json" },
      body: JSON.stringify({ repo, access: "write" }),
      signal: AbortSignal.timeout(15000),
    });
  } catch {
    return fail("couldn't reach your Uno account to sign in to GitHub; try again.");
  }
  let answer = null;
  try {
    answer = await response.json();
  } catch {}
  if (response.status === 200 && answer && typeof answer.token === "string" && answer.token) {
    const lines = ["username=" + (answer.username || "x-access-token"), "password=" + answer.token];
    const expiry = Date.parse(answer.expires_at || "");
    if (Number.isFinite(expiry)) lines.push("password_expiry_utc=" + Math.floor(expiry / 1000));
    process.stdout.write(lines.join("\n") + "\n");
    if (answer.access === "read") {
      process.stderr.write(
        "Uno: signed in to GitHub for " + repo + " (read only: clone and pull work, push is not allowed yet).\n",
      );
    }
    return;
  }
  const code = (answer && (answer.code || answer.error)) || "";
  if (code === "GITHUB_NOT_CONNECTED") {
    return fail(
      "GitHub isn't connected to your Uno account yet. Connect it once in Uno Work (New project → From GitHub → Connect GitHub) and it works on every computer.",
    );
  }
  if (code === "GITHUB_REPO_NOT_ALLOWED") {
    return fail(
      "Uno isn't allowed into " + repo + " on GitHub yet. Add the repository: Uno Work → New project → From GitHub → Connect GitHub.",
    );
  }
  if (code === "CONNECTOR_NOT_ALLOWED") {
    return fail("GitHub is turned off for this assistant (Uno Work → Assistants → Access).");
  }
  // An older console (404 without a code), GitHub down, the App not set up:
  // say nothing, git carries on as it did before this helper existed.
}

main().then(
  () => process.exit(0),
  () => process.exit(0),
);
`;
  // A shebang cannot carry a path with spaces; PATH's node is the fallback.
  const interpreter = /\s/.test(input.nodePath) ? "/usr/bin/env node" : input.nodePath;
  return (
    `#!${interpreter}\n` +
    body
      // Function replacers: a path may contain "$".
      .replace("__SETTINGS_PATH__", () => JSON.stringify(input.settingsPath))
      .replace("__BASE_URL__", () => JSON.stringify(input.baseUrl))
      .trimStart()
  );
}

/** Result of one `git config` call, as the installer needs it. */
export interface GitConfigResult {
  readonly code: number;
  readonly stdout: string;
}

export interface InstallGitCredentialHelperDeps {
  /** Directory the helper file lives in (the daemon's state dir + `/bin`). */
  readonly binDir: string;
  readonly script: string;
  readonly mkdir: (dir: string) => Promise<void>;
  readonly readFile: (path: string) => Promise<string | null>;
  /** Writes atomically with the given mode. */
  readonly writeExecutable: (path: string, content: string) => Promise<void>;
  /** `git config --global <args…>`. */
  readonly gitConfigGlobal: (args: ReadonlyArray<string>) => Promise<GitConfigResult>;
  readonly join: (...parts: ReadonlyArray<string>) => string;
}

export interface InstallGitCredentialHelperResult {
  readonly helperPath: string;
  /** What changed this time (nothing on the second run). */
  readonly wroteScript: boolean;
  readonly addedHelper: boolean;
  readonly setUseHttpPath: boolean;
}

/**
 * Puts the helper file in place and registers it for `https://github.com` in
 * the global git config. Idempotent; helpers that are already configured stay
 * where they are and are asked first.
 */
export async function installGitCredentialHelper(
  deps: InstallGitCredentialHelperDeps,
): Promise<InstallGitCredentialHelperResult> {
  const helperPath = deps.join(deps.binDir, GIT_CREDENTIAL_HELPER_NAME);
  let wroteScript = false;
  if ((await deps.readFile(helperPath)) !== deps.script) {
    await deps.mkdir(deps.binDir);
    await deps.writeExecutable(helperPath, deps.script);
    wroteScript = true;
  }

  const helperKey = `${GITHUB_CREDENTIAL_SECTION}.helper`;
  const existing = await deps.gitConfigGlobal(["--get-all", helperKey]);
  const helpers = existing.code === 0 ? existing.stdout.split("\n").map((line) => line.trim()) : [];
  let addedHelper = false;
  if (!helpers.includes(helperPath)) {
    const added = await deps.gitConfigGlobal(["--add", helperKey, helperPath]);
    if (added.code !== 0) throw new Error(`git config --add ${helperKey} failed (${added.code})`);
    addedHelper = true;
  }

  // Without the path git asks for "github.com" as a whole and the token could
  // not be narrowed to one repository. A value the person set is left alone.
  const pathKey = `${GITHUB_CREDENTIAL_SECTION}.useHttpPath`;
  const current = await deps.gitConfigGlobal(["--get", pathKey]);
  let setUseHttpPath = false;
  if (current.code !== 0 || current.stdout.trim().length === 0) {
    const set = await deps.gitConfigGlobal([pathKey, "true"]);
    if (set.code !== 0) throw new Error(`git config ${pathKey} failed (${set.code})`);
    setUseHttpPath = true;
  }
  return { helperPath, wroteScript, addedHelper, setUseHttpPath };
}
