/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsAssistantRouteImport } from './routes/settings.assistant'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatAssistantRouteImport } from './routes/_chat.assistant'
import { Route as ChatAssistantIndexRouteImport } from './routes/_chat.assistant.index'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatAssistantProjectIdRouteImport } from './routes/_chat.assistant.$projectId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantIndexRoute = ChatAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAssistantRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantProjectIdRoute = ChatAssistantProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ChatAssistantRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/assistant': typeof ChatAssistantRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/assistant/$projectId': typeof ChatAssistantProjectIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/assistant/': typeof ChatAssistantIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/assistant/$projectId': typeof ChatAssistantProjectIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/assistant': typeof ChatAssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/assistant': typeof ChatAssistantRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/assistant/$projectId': typeof ChatAssistantProjectIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/assistant/': typeof ChatAssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/assistant'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/assistant/$projectId'
    | '/draft/$draftId'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/source-control'
    | '/'
    | '/$environmentId/$threadId'
    | '/assistant/$projectId'
    | '/draft/$draftId'
    | '/assistant'
  id:
    | '__root__'
    | '/_chat'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/_chat/assistant'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/assistant/$projectId'
    | '/_chat/draft/$draftId'
    | '/_chat/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/assistant': {
      id: '/_chat/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistant/': {
      id: '/_chat/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ChatAssistantIndexRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistant/$projectId': {
      id: '/_chat/assistant/$projectId'
      path: '/$projectId'
      fullPath: '/assistant/$projectId'
      preLoaderRoute: typeof ChatAssistantProjectIdRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatAssistantRouteChildren {
  ChatAssistantProjectIdRoute: typeof ChatAssistantProjectIdRoute
  ChatAssistantIndexRoute: typeof ChatAssistantIndexRoute
}

const ChatAssistantRouteChildren: ChatAssistantRouteChildren = {
  ChatAssistantProjectIdRoute: ChatAssistantProjectIdRoute,
  ChatAssistantIndexRoute: ChatAssistantIndexRoute,
}

const ChatAssistantRouteWithChildren = ChatAssistantRoute._addFileChildren(
  ChatAssistantRouteChildren,
)

interface ChatRouteChildren {
  ChatAssistantRoute: typeof ChatAssistantRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAssistantRoute: ChatAssistantRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
