/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsVaultRouteImport } from './routes/settings.vault'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings.extensions'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsAssistantRouteImport } from './routes/settings.assistant'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatAssistantRouteImport } from './routes/_chat.assistant'
import { Route as ChatAssistantIndexRouteImport } from './routes/_chat.assistant.index'
import { Route as SettingsEnvironmentEnvironmentIdRouteImport } from './routes/settings.environment.$environmentId'
import { Route as SettingsAppGeneralRouteImport } from './routes/settings.app.general'
import { Route as SettingsAppConnectionsRouteImport } from './routes/settings.app.connections'
import { Route as SettingsAppBrowserRouteImport } from './routes/settings.app.browser'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as SettingsEnvironmentEnvironmentIdSourceControlRouteImport } from './routes/settings.environment.$environmentId.source-control'
import { Route as SettingsEnvironmentEnvironmentIdProvidersRouteImport } from './routes/settings.environment.$environmentId.providers'
import { Route as SettingsEnvironmentEnvironmentIdGeneralRouteImport } from './routes/settings.environment.$environmentId.general'
import { Route as SettingsEnvironmentEnvironmentIdAssistantsRouteImport } from './routes/settings.environment.$environmentId.assistants'
import { Route as SettingsEnvironmentEnvironmentIdArchivedRouteImport } from './routes/settings.environment.$environmentId.archived'
import { Route as ChatAssistantEnvironmentIdProjectIdRouteImport } from './routes/_chat.assistant.$environmentId.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsVaultRoute = SettingsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantIndexRoute = ChatAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAssistantRoute,
} as any)
const SettingsEnvironmentEnvironmentIdRoute =
  SettingsEnvironmentEnvironmentIdRouteImport.update({
    id: '/environment/$environmentId',
    path: '/environment/$environmentId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAppGeneralRoute = SettingsAppGeneralRouteImport.update({
  id: '/app/general',
  path: '/app/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppConnectionsRoute = SettingsAppConnectionsRouteImport.update({
  id: '/app/connections',
  path: '/app/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppBrowserRoute = SettingsAppBrowserRouteImport.update({
  id: '/app/browser',
  path: '/app/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdSourceControlRoute =
  SettingsEnvironmentEnvironmentIdSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdProvidersRoute =
  SettingsEnvironmentEnvironmentIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdGeneralRoute =
  SettingsEnvironmentEnvironmentIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdAssistantsRoute =
  SettingsEnvironmentEnvironmentIdAssistantsRouteImport.update({
    id: '/assistants',
    path: '/assistants',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdArchivedRoute =
  SettingsEnvironmentEnvironmentIdArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const ChatAssistantEnvironmentIdProjectIdRoute =
  ChatAssistantEnvironmentIdProjectIdRouteImport.update({
    id: '/$environmentId/$projectId',
    path: '/$environmentId/$projectId',
    getParentRoute: () => ChatAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/assistant': typeof ChatAssistantRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/assistant/': typeof ChatAssistantIndexRoute
  '/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/assistant': typeof ChatAssistantIndexRoute
  '/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/assistant': typeof ChatAssistantRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/_chat/assistant/': typeof ChatAssistantIndexRoute
  '/_chat/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/assistant'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/source-control'
    | '/settings/vault'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/environment/$environmentId'
    | '/assistant/'
    | '/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/source-control'
    | '/settings/vault'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/environment/$environmentId'
    | '/assistant'
    | '/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  id:
    | '__root__'
    | '/_chat'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/_chat/assistant'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/browser'
    | '/settings/connections'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/source-control'
    | '/settings/vault'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/environment/$environmentId'
    | '/_chat/assistant/'
    | '/_chat/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/vault': {
      id: '/settings/vault'
      path: '/vault'
      fullPath: '/settings/vault'
      preLoaderRoute: typeof SettingsVaultRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/assistant': {
      id: '/_chat/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistant/': {
      id: '/_chat/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ChatAssistantIndexRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
    '/settings/environment/$environmentId': {
      id: '/settings/environment/$environmentId'
      path: '/environment/$environmentId'
      fullPath: '/settings/environment/$environmentId'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/general': {
      id: '/settings/app/general'
      path: '/app/general'
      fullPath: '/settings/app/general'
      preLoaderRoute: typeof SettingsAppGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/connections': {
      id: '/settings/app/connections'
      path: '/app/connections'
      fullPath: '/settings/app/connections'
      preLoaderRoute: typeof SettingsAppConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/browser': {
      id: '/settings/app/browser'
      path: '/app/browser'
      fullPath: '/settings/app/browser'
      preLoaderRoute: typeof SettingsAppBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/environment/$environmentId/source-control': {
      id: '/settings/environment/$environmentId/source-control'
      path: '/source-control'
      fullPath: '/settings/environment/$environmentId/source-control'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdSourceControlRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/providers': {
      id: '/settings/environment/$environmentId/providers'
      path: '/providers'
      fullPath: '/settings/environment/$environmentId/providers'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdProvidersRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/general': {
      id: '/settings/environment/$environmentId/general'
      path: '/general'
      fullPath: '/settings/environment/$environmentId/general'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdGeneralRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/assistants': {
      id: '/settings/environment/$environmentId/assistants'
      path: '/assistants'
      fullPath: '/settings/environment/$environmentId/assistants'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdAssistantsRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/archived': {
      id: '/settings/environment/$environmentId/archived'
      path: '/archived'
      fullPath: '/settings/environment/$environmentId/archived'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdArchivedRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/_chat/assistant/$environmentId/$projectId': {
      id: '/_chat/assistant/$environmentId/$projectId'
      path: '/$environmentId/$projectId'
      fullPath: '/assistant/$environmentId/$projectId'
      preLoaderRoute: typeof ChatAssistantEnvironmentIdProjectIdRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
  }
}

interface ChatAssistantRouteChildren {
  ChatAssistantIndexRoute: typeof ChatAssistantIndexRoute
  ChatAssistantEnvironmentIdProjectIdRoute: typeof ChatAssistantEnvironmentIdProjectIdRoute
}

const ChatAssistantRouteChildren: ChatAssistantRouteChildren = {
  ChatAssistantIndexRoute: ChatAssistantIndexRoute,
  ChatAssistantEnvironmentIdProjectIdRoute:
    ChatAssistantEnvironmentIdProjectIdRoute,
}

const ChatAssistantRouteWithChildren = ChatAssistantRoute._addFileChildren(
  ChatAssistantRouteChildren,
)

interface ChatRouteChildren {
  ChatAssistantRoute: typeof ChatAssistantRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAssistantRoute: ChatAssistantRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsEnvironmentEnvironmentIdRouteChildren {
  SettingsEnvironmentEnvironmentIdArchivedRoute: typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  SettingsEnvironmentEnvironmentIdAssistantsRoute: typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  SettingsEnvironmentEnvironmentIdGeneralRoute: typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  SettingsEnvironmentEnvironmentIdProvidersRoute: typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  SettingsEnvironmentEnvironmentIdSourceControlRoute: typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}

const SettingsEnvironmentEnvironmentIdRouteChildren: SettingsEnvironmentEnvironmentIdRouteChildren =
  {
    SettingsEnvironmentEnvironmentIdArchivedRoute:
      SettingsEnvironmentEnvironmentIdArchivedRoute,
    SettingsEnvironmentEnvironmentIdAssistantsRoute:
      SettingsEnvironmentEnvironmentIdAssistantsRoute,
    SettingsEnvironmentEnvironmentIdGeneralRoute:
      SettingsEnvironmentEnvironmentIdGeneralRoute,
    SettingsEnvironmentEnvironmentIdProvidersRoute:
      SettingsEnvironmentEnvironmentIdProvidersRoute,
    SettingsEnvironmentEnvironmentIdSourceControlRoute:
      SettingsEnvironmentEnvironmentIdSourceControlRoute,
  }

const SettingsEnvironmentEnvironmentIdRouteWithChildren =
  SettingsEnvironmentEnvironmentIdRoute._addFileChildren(
    SettingsEnvironmentEnvironmentIdRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsVaultRoute: typeof SettingsVaultRoute
  SettingsAppBrowserRoute: typeof SettingsAppBrowserRoute
  SettingsAppConnectionsRoute: typeof SettingsAppConnectionsRoute
  SettingsAppGeneralRoute: typeof SettingsAppGeneralRoute
  SettingsEnvironmentEnvironmentIdRoute: typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsVaultRoute: SettingsVaultRoute,
  SettingsAppBrowserRoute: SettingsAppBrowserRoute,
  SettingsAppConnectionsRoute: SettingsAppConnectionsRoute,
  SettingsAppGeneralRoute: SettingsAppGeneralRoute,
  SettingsEnvironmentEnvironmentIdRoute:
    SettingsEnvironmentEnvironmentIdRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
