/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'
import { Route as SettingsVaultRouteImport } from './routes/settings.vault'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings.extensions'
import { Route as SettingsDeveloperRouteImport } from './routes/settings.developer'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsComputerAccessRouteImport } from './routes/settings.computer-access'
import { Route as SettingsComputerRouteImport } from './routes/settings.computer'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsAssistantsPhoneRouteImport } from './routes/settings.assistants-phone'
import { Route as SettingsAssistantRouteImport } from './routes/settings.assistant'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ChatSitesRouteImport } from './routes/_chat.sites'
import { Route as ChatSetupRouteImport } from './routes/_chat.setup'
import { Route as ChatProjectsRouteImport } from './routes/_chat.projects'
import { Route as ChatOfficeRouteImport } from './routes/_chat.office'
import { Route as ChatMyUnoRouteImport } from './routes/_chat.my-uno'
import { Route as ChatFilesRouteImport } from './routes/_chat.files'
import { Route as ChatDriveRouteImport } from './routes/_chat.drive'
import { Route as ChatComputerRouteImport } from './routes/_chat.computer'
import { Route as ChatAssistantsRouteImport } from './routes/_chat.assistants'
import { Route as ChatAssistantRouteImport } from './routes/_chat.assistant'
import { Route as ChatAppRouteImport } from './routes/_chat.app'
import { Route as ChatAiRouteImport } from './routes/_chat.ai'
import { Route as ChatAssistantIndexRouteImport } from './routes/_chat.assistant.index'
import { Route as SettingsEnvironmentEnvironmentIdRouteImport } from './routes/settings.environment.$environmentId'
import { Route as SettingsAppPhoneRouteImport } from './routes/settings.app.phone'
import { Route as SettingsAppLabsRouteImport } from './routes/settings.app.labs'
import { Route as SettingsAppGeneralRouteImport } from './routes/settings.app.general'
import { Route as SettingsAppConnectionsRouteImport } from './routes/settings.app.connections'
import { Route as SettingsAppBrowserRouteImport } from './routes/settings.app.browser'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as SettingsEnvironmentEnvironmentIdSourceControlRouteImport } from './routes/settings.environment.$environmentId.source-control'
import { Route as SettingsEnvironmentEnvironmentIdProvidersRouteImport } from './routes/settings.environment.$environmentId.providers'
import { Route as SettingsEnvironmentEnvironmentIdHarnessesRouteImport } from './routes/settings.environment.$environmentId.harnesses'
import { Route as SettingsEnvironmentEnvironmentIdGeneralRouteImport } from './routes/settings.environment.$environmentId.general'
import { Route as SettingsEnvironmentEnvironmentIdAssistantsRouteImport } from './routes/settings.environment.$environmentId.assistants'
import { Route as SettingsEnvironmentEnvironmentIdArchivedRouteImport } from './routes/settings.environment.$environmentId.archived'
import { Route as SettingsEnvironmentEnvironmentIdAppsRouteImport } from './routes/settings.environment.$environmentId.apps'
import { Route as ChatAssistantEnvironmentIdProjectIdRouteImport } from './routes/_chat.assistant.$environmentId.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVaultRoute = SettingsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDeveloperRoute = SettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsComputerAccessRoute = SettingsComputerAccessRouteImport.update({
  id: '/computer-access',
  path: '/computer-access',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsComputerRoute = SettingsComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAssistantsPhoneRoute = SettingsAssistantsPhoneRouteImport.update({
  id: '/assistants-phone',
  path: '/assistants-phone',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSitesRoute = ChatSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSetupRoute = ChatSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ChatRoute,
} as any)
const ChatProjectsRoute = ChatProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ChatRoute,
} as any)
const ChatOfficeRoute = ChatOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => ChatRoute,
} as any)
const ChatMyUnoRoute = ChatMyUnoRouteImport.update({
  id: '/my-uno',
  path: '/my-uno',
  getParentRoute: () => ChatRoute,
} as any)
const ChatFilesRoute = ChatFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDriveRoute = ChatDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => ChatRoute,
} as any)
const ChatComputerRoute = ChatComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantsRoute = ChatAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAppRoute = ChatAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAiRoute = ChatAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantIndexRoute = ChatAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAssistantRoute,
} as any)
const SettingsEnvironmentEnvironmentIdRoute =
  SettingsEnvironmentEnvironmentIdRouteImport.update({
    id: '/environment/$environmentId',
    path: '/environment/$environmentId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAppPhoneRoute = SettingsAppPhoneRouteImport.update({
  id: '/app/phone',
  path: '/app/phone',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppLabsRoute = SettingsAppLabsRouteImport.update({
  id: '/app/labs',
  path: '/app/labs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppGeneralRoute = SettingsAppGeneralRouteImport.update({
  id: '/app/general',
  path: '/app/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppConnectionsRoute = SettingsAppConnectionsRouteImport.update({
  id: '/app/connections',
  path: '/app/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppBrowserRoute = SettingsAppBrowserRouteImport.update({
  id: '/app/browser',
  path: '/app/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdSourceControlRoute =
  SettingsEnvironmentEnvironmentIdSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdProvidersRoute =
  SettingsEnvironmentEnvironmentIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdHarnessesRoute =
  SettingsEnvironmentEnvironmentIdHarnessesRouteImport.update({
    id: '/harnesses',
    path: '/harnesses',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdGeneralRoute =
  SettingsEnvironmentEnvironmentIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdAssistantsRoute =
  SettingsEnvironmentEnvironmentIdAssistantsRouteImport.update({
    id: '/assistants',
    path: '/assistants',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdArchivedRoute =
  SettingsEnvironmentEnvironmentIdArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const SettingsEnvironmentEnvironmentIdAppsRoute =
  SettingsEnvironmentEnvironmentIdAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => SettingsEnvironmentEnvironmentIdRoute,
  } as any)
const ChatAssistantEnvironmentIdProjectIdRoute =
  ChatAssistantEnvironmentIdProjectIdRouteImport.update({
    id: '/$environmentId/$projectId',
    path: '/$environmentId/$projectId',
    getParentRoute: () => ChatAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ai': typeof ChatAiRoute
  '/app': typeof ChatAppRoute
  '/assistant': typeof ChatAssistantRouteWithChildren
  '/assistants': typeof ChatAssistantsRoute
  '/computer': typeof ChatComputerRoute
  '/drive': typeof ChatDriveRoute
  '/files': typeof ChatFilesRoute
  '/my-uno': typeof ChatMyUnoRoute
  '/office': typeof ChatOfficeRoute
  '/projects': typeof ChatProjectsRoute
  '/setup': typeof ChatSetupRoute
  '/sites': typeof ChatSitesRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/assistants-phone': typeof SettingsAssistantsPhoneRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/computer': typeof SettingsComputerRoute
  '/settings/computer-access': typeof SettingsComputerAccessRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/app/labs': typeof SettingsAppLabsRoute
  '/settings/app/phone': typeof SettingsAppPhoneRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/assistant/': typeof ChatAssistantIndexRoute
  '/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/apps': typeof SettingsEnvironmentEnvironmentIdAppsRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/harnesses': typeof SettingsEnvironmentEnvironmentIdHarnessesRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ai': typeof ChatAiRoute
  '/app': typeof ChatAppRoute
  '/assistants': typeof ChatAssistantsRoute
  '/computer': typeof ChatComputerRoute
  '/drive': typeof ChatDriveRoute
  '/files': typeof ChatFilesRoute
  '/my-uno': typeof ChatMyUnoRoute
  '/office': typeof ChatOfficeRoute
  '/projects': typeof ChatProjectsRoute
  '/setup': typeof ChatSetupRoute
  '/sites': typeof ChatSitesRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/assistants-phone': typeof SettingsAssistantsPhoneRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/computer': typeof SettingsComputerRoute
  '/settings/computer-access': typeof SettingsComputerAccessRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/app/labs': typeof SettingsAppLabsRoute
  '/settings/app/phone': typeof SettingsAppPhoneRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/assistant': typeof ChatAssistantIndexRoute
  '/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/apps': typeof SettingsEnvironmentEnvironmentIdAppsRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/harnesses': typeof SettingsEnvironmentEnvironmentIdHarnessesRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/ai': typeof ChatAiRoute
  '/_chat/app': typeof ChatAppRoute
  '/_chat/assistant': typeof ChatAssistantRouteWithChildren
  '/_chat/assistants': typeof ChatAssistantsRoute
  '/_chat/computer': typeof ChatComputerRoute
  '/_chat/drive': typeof ChatDriveRoute
  '/_chat/files': typeof ChatFilesRoute
  '/_chat/my-uno': typeof ChatMyUnoRoute
  '/_chat/office': typeof ChatOfficeRoute
  '/_chat/projects': typeof ChatProjectsRoute
  '/_chat/setup': typeof ChatSetupRoute
  '/_chat/sites': typeof ChatSitesRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/assistants-phone': typeof SettingsAssistantsPhoneRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/computer': typeof SettingsComputerRoute
  '/settings/computer-access': typeof SettingsComputerAccessRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/settings/app/browser': typeof SettingsAppBrowserRoute
  '/settings/app/connections': typeof SettingsAppConnectionsRoute
  '/settings/app/general': typeof SettingsAppGeneralRoute
  '/settings/app/labs': typeof SettingsAppLabsRoute
  '/settings/app/phone': typeof SettingsAppPhoneRoute
  '/settings/environment/$environmentId': typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
  '/_chat/assistant/': typeof ChatAssistantIndexRoute
  '/_chat/assistant/$environmentId/$projectId': typeof ChatAssistantEnvironmentIdProjectIdRoute
  '/settings/environment/$environmentId/apps': typeof SettingsEnvironmentEnvironmentIdAppsRoute
  '/settings/environment/$environmentId/archived': typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  '/settings/environment/$environmentId/assistants': typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  '/settings/environment/$environmentId/general': typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  '/settings/environment/$environmentId/harnesses': typeof SettingsEnvironmentEnvironmentIdHarnessesRoute
  '/settings/environment/$environmentId/providers': typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  '/settings/environment/$environmentId/source-control': typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/ai'
    | '/app'
    | '/assistant'
    | '/assistants'
    | '/computer'
    | '/drive'
    | '/files'
    | '/my-uno'
    | '/office'
    | '/projects'
    | '/setup'
    | '/sites'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/assistants-phone'
    | '/settings/browser'
    | '/settings/computer'
    | '/settings/computer-access'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/security'
    | '/settings/source-control'
    | '/settings/vault'
    | '/settings/workspace'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/app/labs'
    | '/settings/app/phone'
    | '/settings/environment/$environmentId'
    | '/assistant/'
    | '/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/apps'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/harnesses'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/ai'
    | '/app'
    | '/assistants'
    | '/computer'
    | '/drive'
    | '/files'
    | '/my-uno'
    | '/office'
    | '/projects'
    | '/setup'
    | '/sites'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/assistants-phone'
    | '/settings/browser'
    | '/settings/computer'
    | '/settings/computer-access'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/security'
    | '/settings/source-control'
    | '/settings/vault'
    | '/settings/workspace'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/app/labs'
    | '/settings/app/phone'
    | '/settings/environment/$environmentId'
    | '/assistant'
    | '/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/apps'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/harnesses'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  id:
    | '__root__'
    | '/_chat'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/_chat/ai'
    | '/_chat/app'
    | '/_chat/assistant'
    | '/_chat/assistants'
    | '/_chat/computer'
    | '/_chat/drive'
    | '/_chat/files'
    | '/_chat/my-uno'
    | '/_chat/office'
    | '/_chat/projects'
    | '/_chat/setup'
    | '/_chat/sites'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/archived'
    | '/settings/assistant'
    | '/settings/assistants-phone'
    | '/settings/browser'
    | '/settings/computer'
    | '/settings/computer-access'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/security'
    | '/settings/source-control'
    | '/settings/vault'
    | '/settings/workspace'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/settings/app/browser'
    | '/settings/app/connections'
    | '/settings/app/general'
    | '/settings/app/labs'
    | '/settings/app/phone'
    | '/settings/environment/$environmentId'
    | '/_chat/assistant/'
    | '/_chat/assistant/$environmentId/$projectId'
    | '/settings/environment/$environmentId/apps'
    | '/settings/environment/$environmentId/archived'
    | '/settings/environment/$environmentId/assistants'
    | '/settings/environment/$environmentId/general'
    | '/settings/environment/$environmentId/harnesses'
    | '/settings/environment/$environmentId/providers'
    | '/settings/environment/$environmentId/source-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/vault': {
      id: '/settings/vault'
      path: '/vault'
      fullPath: '/settings/vault'
      preLoaderRoute: typeof SettingsVaultRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/developer': {
      id: '/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof SettingsDeveloperRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/computer-access': {
      id: '/settings/computer-access'
      path: '/computer-access'
      fullPath: '/settings/computer-access'
      preLoaderRoute: typeof SettingsComputerAccessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/computer': {
      id: '/settings/computer'
      path: '/computer'
      fullPath: '/settings/computer'
      preLoaderRoute: typeof SettingsComputerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/assistants-phone': {
      id: '/settings/assistants-phone'
      path: '/assistants-phone'
      fullPath: '/settings/assistants-phone'
      preLoaderRoute: typeof SettingsAssistantsPhoneRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/sites': {
      id: '/_chat/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof ChatSitesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/setup': {
      id: '/_chat/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ChatSetupRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/projects': {
      id: '/_chat/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ChatProjectsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/office': {
      id: '/_chat/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof ChatOfficeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/my-uno': {
      id: '/_chat/my-uno'
      path: '/my-uno'
      fullPath: '/my-uno'
      preLoaderRoute: typeof ChatMyUnoRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/files': {
      id: '/_chat/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof ChatFilesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/drive': {
      id: '/_chat/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof ChatDriveRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/computer': {
      id: '/_chat/computer'
      path: '/computer'
      fullPath: '/computer'
      preLoaderRoute: typeof ChatComputerRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistants': {
      id: '/_chat/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof ChatAssistantsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistant': {
      id: '/_chat/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/app': {
      id: '/_chat/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ChatAppRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/ai': {
      id: '/_chat/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof ChatAiRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/assistant/': {
      id: '/_chat/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ChatAssistantIndexRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
    '/settings/environment/$environmentId': {
      id: '/settings/environment/$environmentId'
      path: '/environment/$environmentId'
      fullPath: '/settings/environment/$environmentId'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/phone': {
      id: '/settings/app/phone'
      path: '/app/phone'
      fullPath: '/settings/app/phone'
      preLoaderRoute: typeof SettingsAppPhoneRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/labs': {
      id: '/settings/app/labs'
      path: '/app/labs'
      fullPath: '/settings/app/labs'
      preLoaderRoute: typeof SettingsAppLabsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/general': {
      id: '/settings/app/general'
      path: '/app/general'
      fullPath: '/settings/app/general'
      preLoaderRoute: typeof SettingsAppGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/connections': {
      id: '/settings/app/connections'
      path: '/app/connections'
      fullPath: '/settings/app/connections'
      preLoaderRoute: typeof SettingsAppConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app/browser': {
      id: '/settings/app/browser'
      path: '/app/browser'
      fullPath: '/settings/app/browser'
      preLoaderRoute: typeof SettingsAppBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/environment/$environmentId/source-control': {
      id: '/settings/environment/$environmentId/source-control'
      path: '/source-control'
      fullPath: '/settings/environment/$environmentId/source-control'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdSourceControlRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/providers': {
      id: '/settings/environment/$environmentId/providers'
      path: '/providers'
      fullPath: '/settings/environment/$environmentId/providers'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdProvidersRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/harnesses': {
      id: '/settings/environment/$environmentId/harnesses'
      path: '/harnesses'
      fullPath: '/settings/environment/$environmentId/harnesses'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdHarnessesRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/general': {
      id: '/settings/environment/$environmentId/general'
      path: '/general'
      fullPath: '/settings/environment/$environmentId/general'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdGeneralRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/assistants': {
      id: '/settings/environment/$environmentId/assistants'
      path: '/assistants'
      fullPath: '/settings/environment/$environmentId/assistants'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdAssistantsRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/archived': {
      id: '/settings/environment/$environmentId/archived'
      path: '/archived'
      fullPath: '/settings/environment/$environmentId/archived'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdArchivedRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/settings/environment/$environmentId/apps': {
      id: '/settings/environment/$environmentId/apps'
      path: '/apps'
      fullPath: '/settings/environment/$environmentId/apps'
      preLoaderRoute: typeof SettingsEnvironmentEnvironmentIdAppsRouteImport
      parentRoute: typeof SettingsEnvironmentEnvironmentIdRoute
    }
    '/_chat/assistant/$environmentId/$projectId': {
      id: '/_chat/assistant/$environmentId/$projectId'
      path: '/$environmentId/$projectId'
      fullPath: '/assistant/$environmentId/$projectId'
      preLoaderRoute: typeof ChatAssistantEnvironmentIdProjectIdRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
  }
}

interface ChatAssistantRouteChildren {
  ChatAssistantIndexRoute: typeof ChatAssistantIndexRoute
  ChatAssistantEnvironmentIdProjectIdRoute: typeof ChatAssistantEnvironmentIdProjectIdRoute
}

const ChatAssistantRouteChildren: ChatAssistantRouteChildren = {
  ChatAssistantIndexRoute: ChatAssistantIndexRoute,
  ChatAssistantEnvironmentIdProjectIdRoute:
    ChatAssistantEnvironmentIdProjectIdRoute,
}

const ChatAssistantRouteWithChildren = ChatAssistantRoute._addFileChildren(
  ChatAssistantRouteChildren,
)

interface ChatRouteChildren {
  ChatAiRoute: typeof ChatAiRoute
  ChatAppRoute: typeof ChatAppRoute
  ChatAssistantRoute: typeof ChatAssistantRouteWithChildren
  ChatAssistantsRoute: typeof ChatAssistantsRoute
  ChatComputerRoute: typeof ChatComputerRoute
  ChatDriveRoute: typeof ChatDriveRoute
  ChatFilesRoute: typeof ChatFilesRoute
  ChatMyUnoRoute: typeof ChatMyUnoRoute
  ChatOfficeRoute: typeof ChatOfficeRoute
  ChatProjectsRoute: typeof ChatProjectsRoute
  ChatSetupRoute: typeof ChatSetupRoute
  ChatSitesRoute: typeof ChatSitesRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAiRoute: ChatAiRoute,
  ChatAppRoute: ChatAppRoute,
  ChatAssistantRoute: ChatAssistantRouteWithChildren,
  ChatAssistantsRoute: ChatAssistantsRoute,
  ChatComputerRoute: ChatComputerRoute,
  ChatDriveRoute: ChatDriveRoute,
  ChatFilesRoute: ChatFilesRoute,
  ChatMyUnoRoute: ChatMyUnoRoute,
  ChatOfficeRoute: ChatOfficeRoute,
  ChatProjectsRoute: ChatProjectsRoute,
  ChatSetupRoute: ChatSetupRoute,
  ChatSitesRoute: ChatSitesRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsEnvironmentEnvironmentIdRouteChildren {
  SettingsEnvironmentEnvironmentIdAppsRoute: typeof SettingsEnvironmentEnvironmentIdAppsRoute
  SettingsEnvironmentEnvironmentIdArchivedRoute: typeof SettingsEnvironmentEnvironmentIdArchivedRoute
  SettingsEnvironmentEnvironmentIdAssistantsRoute: typeof SettingsEnvironmentEnvironmentIdAssistantsRoute
  SettingsEnvironmentEnvironmentIdGeneralRoute: typeof SettingsEnvironmentEnvironmentIdGeneralRoute
  SettingsEnvironmentEnvironmentIdHarnessesRoute: typeof SettingsEnvironmentEnvironmentIdHarnessesRoute
  SettingsEnvironmentEnvironmentIdProvidersRoute: typeof SettingsEnvironmentEnvironmentIdProvidersRoute
  SettingsEnvironmentEnvironmentIdSourceControlRoute: typeof SettingsEnvironmentEnvironmentIdSourceControlRoute
}

const SettingsEnvironmentEnvironmentIdRouteChildren: SettingsEnvironmentEnvironmentIdRouteChildren =
  {
    SettingsEnvironmentEnvironmentIdAppsRoute:
      SettingsEnvironmentEnvironmentIdAppsRoute,
    SettingsEnvironmentEnvironmentIdArchivedRoute:
      SettingsEnvironmentEnvironmentIdArchivedRoute,
    SettingsEnvironmentEnvironmentIdAssistantsRoute:
      SettingsEnvironmentEnvironmentIdAssistantsRoute,
    SettingsEnvironmentEnvironmentIdGeneralRoute:
      SettingsEnvironmentEnvironmentIdGeneralRoute,
    SettingsEnvironmentEnvironmentIdHarnessesRoute:
      SettingsEnvironmentEnvironmentIdHarnessesRoute,
    SettingsEnvironmentEnvironmentIdProvidersRoute:
      SettingsEnvironmentEnvironmentIdProvidersRoute,
    SettingsEnvironmentEnvironmentIdSourceControlRoute:
      SettingsEnvironmentEnvironmentIdSourceControlRoute,
  }

const SettingsEnvironmentEnvironmentIdRouteWithChildren =
  SettingsEnvironmentEnvironmentIdRoute._addFileChildren(
    SettingsEnvironmentEnvironmentIdRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsAssistantsPhoneRoute: typeof SettingsAssistantsPhoneRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsComputerRoute: typeof SettingsComputerRoute
  SettingsComputerAccessRoute: typeof SettingsComputerAccessRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDeveloperRoute: typeof SettingsDeveloperRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsVaultRoute: typeof SettingsVaultRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsAppBrowserRoute: typeof SettingsAppBrowserRoute
  SettingsAppConnectionsRoute: typeof SettingsAppConnectionsRoute
  SettingsAppGeneralRoute: typeof SettingsAppGeneralRoute
  SettingsAppLabsRoute: typeof SettingsAppLabsRoute
  SettingsAppPhoneRoute: typeof SettingsAppPhoneRoute
  SettingsEnvironmentEnvironmentIdRoute: typeof SettingsEnvironmentEnvironmentIdRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAssistantsPhoneRoute: SettingsAssistantsPhoneRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsComputerRoute: SettingsComputerRoute,
  SettingsComputerAccessRoute: SettingsComputerAccessRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDeveloperRoute: SettingsDeveloperRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsVaultRoute: SettingsVaultRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsAppBrowserRoute: SettingsAppBrowserRoute,
  SettingsAppConnectionsRoute: SettingsAppConnectionsRoute,
  SettingsAppGeneralRoute: SettingsAppGeneralRoute,
  SettingsAppLabsRoute: SettingsAppLabsRoute,
  SettingsAppPhoneRoute: SettingsAppPhoneRoute,
  SettingsEnvironmentEnvironmentIdRoute:
    SettingsEnvironmentEnvironmentIdRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
