/**
 * Instruction layers — one merged text agents actually read, assembled from
 * three sources with a fixed precedence:
 *
 *   repository (`AGENTS.md`, from git) → workspace (registry) → machine (local)
 *
 * The machine layer is last because it is the one that describes physical
 * truth: "there is no AVX2 here", "the daemon runs under systemd". A workspace
 * rule that contradicts the hardware loses.
 *
 * The merged text is written to `.t3code/UNO_WORKSPACE.md` (generated,
 * gitignored) and `AGENTS.md` gets a three-line pointer between markers.
 * Two rules make that safe to run repeatedly:
 *
 * - Text outside the markers is never touched.
 * - A user who deletes the marker block does not get it back. Re-adding it
 *   would be the tool arguing with a person about their own file.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

export const GENERATED_INSTRUCTIONS_RELATIVE_PATH = ".t3code/UNO_WORKSPACE.md";
export const WORKSPACE_INSTRUCTIONS_SCOPE = "*";

const MARKER_BEGIN = "<!-- uno-workspace:begin -->";
const MARKER_END = "<!-- uno-workspace:end -->";

export interface InstructionLayerInput {
  readonly repository: string;
  readonly workspace: string;
  readonly machine: string;
}

export function mergeInstructionLayers(input: InstructionLayerInput): string {
  const sections: string[] = [];
  if (input.repository.trim().length > 0) {
    sections.push(`## Repository\n\n${input.repository.trim()}`);
  }
  if (input.workspace.trim().length > 0) {
    sections.push(`## Workspace\n\n${input.workspace.trim()}`);
  }
  if (input.machine.trim().length > 0) {
    sections.push(`## This machine\n\n${input.machine.trim()}`);
  }
  if (sections.length === 0) return "";
  return [
    "# Uno Workspace instructions",
    "",
    "Generated by Uno Work. Edit the workspace and machine layers in Settings → Workspace.",
    "",
    ...sections,
    "",
  ].join("\n");
}

export function buildPointerBlock(relativePath: string): string {
  return [
    MARKER_BEGIN,
    `Workspace and machine instructions for this checkout live in \`${relativePath}\`.`,
    "Read that file before starting work; it is regenerated by Uno Work.",
    MARKER_END,
  ].join("\n");
}

/**
 * Returns the new `AGENTS.md` body, or `null` when nothing should be written:
 * the file has no marker block *and* the caller asked not to create one, or the
 * existing block is already identical.
 */
export function applyPointerBlock(
  existing: string,
  relativePath: string,
  options: { readonly createIfMissing: boolean },
): string | null {
  const block = buildPointerBlock(relativePath);
  const beginIndex = existing.indexOf(MARKER_BEGIN);
  const endIndex = existing.indexOf(MARKER_END);

  if (beginIndex !== -1 && endIndex !== -1 && endIndex > beginIndex) {
    const before = existing.slice(0, beginIndex);
    const after = existing.slice(endIndex + MARKER_END.length);
    const next = `${before}${block}${after}`;
    return next === existing ? null : next;
  }

  // A half-present block (one marker, the other deleted) is left alone: we
  // cannot tell which half is the user's text.
  if (beginIndex !== -1 || endIndex !== -1) return null;
  if (!options.createIfMissing) return null;

  const separator = existing.trim().length === 0 ? "" : "\n\n";
  return `${existing.trimEnd()}${separator}${block}\n`;
}

export async function readRepositoryInstructions(projectPath: string): Promise<string> {
  for (const candidate of ["AGENTS.md", "CLAUDE.md"]) {
    try {
      const raw = await readFile(join(projectPath, candidate), "utf8");
      // The pointer block is ours, not the repository's; including it would
      // make the merged file quote itself.
      return stripPointerBlock(raw).trim();
    } catch {
      continue;
    }
  }
  return "";
}

export function stripPointerBlock(text: string): string {
  const beginIndex = text.indexOf(MARKER_BEGIN);
  const endIndex = text.indexOf(MARKER_END);
  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) return text;
  return `${text.slice(0, beginIndex)}${text.slice(endIndex + MARKER_END.length)}`;
}

export interface WriteInstructionsResult {
  readonly generatedPath: string;
  readonly pointerWritten: boolean;
  readonly merged: string;
}

export async function writeInstructionFiles(input: {
  readonly projectPath: string;
  readonly layers: InstructionLayerInput;
  readonly createPointerIfMissing: boolean;
}): Promise<WriteInstructionsResult> {
  const merged = mergeInstructionLayers(input.layers);
  const generatedPath = join(input.projectPath, GENERATED_INSTRUCTIONS_RELATIVE_PATH);
  await mkdir(dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, merged, "utf8");

  const agentsPath = join(input.projectPath, "AGENTS.md");
  let existing = "";
  try {
    existing = await readFile(agentsPath, "utf8");
  } catch {
    existing = "";
  }
  const next = applyPointerBlock(existing, GENERATED_INSTRUCTIONS_RELATIVE_PATH, {
    createIfMissing: input.createPointerIfMissing,
  });
  if (next !== null) {
    await writeFile(agentsPath, next, "utf8");
  }
  return {
    generatedPath,
    pointerWritten: next !== null,
    merged,
  };
}
