/**
 * Embeds docs/custom-harness.md and the ACP echo example into the daemon, so
 * every machine gets `~/.uno/docs/` from the daemon it runs — an agent asked
 * to "add my agent to Uno Work" reads the contract from disk.
 *
 *   node apps/server/scripts/embed-harness-guide.ts          # regenerate
 *   node apps/server/scripts/embed-harness-guide.ts --check  # fail if stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
export const SOURCES = {
  guide: "docs/custom-harness.md",
  echoHarness: "examples/acp-echo-harness/echo-harness.mjs",
} as const;
export const TARGET = "apps/server/src/provider/customHarness/harnessGuide.generated.ts";

export function renderBundle(read: (file: string) => string): string {
  const entries = Object.entries(SOURCES)
    .map(([key, file]) => `  /** ${file} */\n  ${key}: ${JSON.stringify(read(file))},`)
    .join("\n");
  return `// GENERATED by apps/server/scripts/embed-harness-guide.ts — do not edit.\n// Sources: docs/custom-harness.md, examples/acp-echo-harness. Regenerate after changing them.\nexport const HARNESS_GUIDE_BUNDLE = {\n${entries}\n} as const;\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const next = renderBundle((file) => readFileSync(path.join(root, file), "utf8"));
  const target = path.join(root, TARGET);
  if (process.argv.includes("--check")) {
    const current = readFileSync(target, "utf8");
    if (current !== next) {
      console.error(`${TARGET} is stale: run node apps/server/scripts/embed-harness-guide.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(target, next);
    console.log(`wrote ${TARGET}`);
  }
}
