/**
 * Embeds the App SDK files (packages/app-sdk, sdk/python) into the daemon, so
 * every machine gets `~/.uno/sdk/` from the daemon it runs — no npm/PyPI
 * needed for an agent building an app on the machine.
 *
 *   node apps/server/scripts/embed-app-sdk.ts          # regenerate
 *   node apps/server/scripts/embed-app-sdk.ts --check  # fail if stale (CI / tests)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
export const SOURCES = {
  jsModule: "packages/app-sdk/src/uno-app.mjs",
  jsTypes: "packages/app-sdk/src/uno-app.d.ts",
  python: "sdk/python/uno_app.py",
} as const;
export const TARGET = "apps/server/src/appSdk/sdkBundle.generated.ts";

export function renderBundle(read: (file: string) => string): string {
  const entries = Object.entries(SOURCES)
    .map(([key, file]) => `  /** ${file} */\n  ${key}: ${JSON.stringify(read(file))},`)
    .join("\n");
  return `// GENERATED by apps/server/scripts/embed-app-sdk.ts — do not edit.\n// Sources: packages/app-sdk, sdk/python. Regenerate after changing them.\nexport const APP_SDK_BUNDLE = {\n${entries}\n} as const;\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const next = renderBundle((file) => readFileSync(path.join(root, file), "utf8"));
  const target = path.join(root, TARGET);
  if (process.argv.includes("--check")) {
    const current = readFileSync(target, "utf8");
    if (current !== next) {
      console.error(`${TARGET} is stale: run node apps/server/scripts/embed-app-sdk.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(target, next);
    console.log(`wrote ${TARGET}`);
  }
}
