/**
 * Embeds the Uno Work environment brief (`apps/server/src/agentContext/
 * unoWorkBrief.md`, the one source of truth for what every AI in Uno Work is
 * told) into the daemon as a TS string, so the bundled server needs no
 * loose .md file next to it.
 *
 *   node apps/server/scripts/embed-agent-context.ts          # regenerate
 *   node apps/server/scripts/embed-agent-context.ts --check  # fail if stale (CI / tests)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
export const SOURCE = "apps/server/src/agentContext/unoWorkBrief.md";
export const TARGET = "apps/server/src/agentContext/unoWorkBrief.generated.ts";

export function renderBrief(markdown: string): string {
  return `// GENERATED by apps/server/scripts/embed-agent-context.ts — do not edit.\n// Source: ${SOURCE}. Regenerate after changing it.\nexport const UNO_WORK_BRIEF_MARKDOWN = ${JSON.stringify(markdown)};\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const next = renderBrief(readFileSync(path.join(root, SOURCE), "utf8"));
  const target = path.join(root, TARGET);
  if (process.argv.includes("--check")) {
    const current = readFileSync(target, "utf8");
    if (current !== next) {
      console.error(`${TARGET} is stale: run node apps/server/scripts/embed-agent-context.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(target, next);
    console.log(`wrote ${TARGET}`);
  }
}
